markdown: rdiscount
permalink: /:title/
url: http://rdongxie.github
name: Red
author: rdongxie
qq: 185770552
email: rdongxie@gmail.com
duoshuo: rdongxie
beian: nothing
cnzz: 88888888
weibo: rdongxie
github: rdongxie
pygments: true
safe: true
paginate: 20
about: "----"
